apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: chat
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chat
    spec:
      containers:
      - image: pythonrocks/chat-carbon:1.0.0
        name: chat-carbon
        resources: {}
status: {}
